"""Local dashboard backend (Bucket 7): FastAPI serving benchmark results + live stats.

Two data sources, both already produced elsewhere -- this layer just serves them:

- `GET /api/results` reads the saved benchmark JSONs from `benchmark/results/`
  (baseline, conflict, cost, forgetting, tokens, storage) -- regenerated by
  `python -m benchmark.harness`.
- `GET /api/stats` returns live pipeline state by delegating to
  `mcp_server.server.memory_stats` (the same aggregation the MCP tool exposes --
  single source of truth, no re-implementation).

`GET /` serves the single-page Chart.js frontend from `dashboard/static/`,
which is fully self-contained (Chart.js is vendored locally, not from a CDN) so
the dashboard honors the project's offline guarantee end to end. Local-only,
no auth -- same trust model as the MCP server.
"""

from __future__ import annotations

import json

from fastapi import FastAPI
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from core import live_metrics
from core.config import REPO_ROOT
from mcp_server.server import memory_stats

RESULTS_DIR = REPO_ROOT / "benchmark" / "results"
STATIC_DIR = REPO_ROOT / "dashboard" / "static"

app = FastAPI(title="memory-layer dashboard")


@app.get("/api/results")
async def api_results() -> dict:
    """All saved benchmark result JSONs, keyed by label (filename stem).

    A half-written or unreadable file is skipped rather than failing the whole
    response -- mirrors `memory_stats`'s tolerance for a mid-regeneration
    results dir.
    """
    results: dict[str, dict] = {}
    if RESULTS_DIR.exists():
        for path in sorted(RESULTS_DIR.glob("*.json")):
            try:
                results[path.stem] = json.loads(path.read_text())
            except (json.JSONDecodeError, OSError):
                continue
    return results


@app.get("/api/stats")
async def api_stats() -> dict:
    """Live pipeline stats (current fact tiers + cost + benchmarks)."""
    return await memory_stats()


@app.get("/api/live")
async def api_live(dataset: str = "main_dataset") -> dict:
    """Everything the dashboard charts render, all computed from the live
    dataset -- no benchmark JSONs involved.

    Composes the resolver/cost view (`memory_stats`, reused as the single source
    of truth for fact counts + the cost ledger) with the read-only
    `live_metrics` (token savings, storage growth, revision counts) derived from
    the dataset's real write history. Read-only: safe to poll on a timer.
    """
    stats = await memory_stats(dataset)
    live = live_metrics.live_report(dataset)
    return {
        "dataset": dataset,
        "facts": stats["facts"],
        "cost": stats["cost"],
        "tokens": live["tokens"],
        "storage": live["storage"],
        "revisions": live["revisions"],
    }


@app.get("/")
async def index() -> FileResponse:
    """Serve the single-page dashboard."""
    return FileResponse(STATIC_DIR / "index.html")


# Mount the static assets (app.js, style.css, vendored chart.umd.min.js) last so
# the explicit routes above take precedence over the static handler.
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")


def main() -> None:
    """Run the dashboard on localhost. Launch: `uv run python -m dashboard.app`."""
    import uvicorn

    uvicorn.run(app, host="127.0.0.1", port=8000)


if __name__ == "__main__":
    main()
